name: Discord Repository Updates

on:
  push:
  pull_request:
  issues:
  release:

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: discord-webhook
        uses: johnnyhuy/actions-discord-git-webhook@v1.0.4
        with:
          webhook_url: ${{ secrets.DISCORD_WEBHOOK }}
